// Canonical sub-topic lists for every CBSE Class 12 PCM chapter that
// appears in the schedule. Used by the structured task-review form so
// Shweta can rate Shikhar's grasp on each individual sub-topic instead of
// giving one global rating per task.
//
// Keys MUST exactly match the chapterName values produced by mkTask() in
// App.tsx (PHYS_CH / CHEM_CH / MATH_CH arrays).
export const CHAPTER_SUBTOPICS: Record<string, string[]> = {
  // ================= PHYSICS =================
  "Electric Charges and Fields": [
    "Electric charge & quantization",
    "Coulomb's law",
    "Forces between multiple charges (superposition)",
    "Electric field & field lines",
    "Electric dipole & dipole moment",
    "Dipole in uniform external field",
    "Electric flux",
    "Gauss's law",
    "Applications of Gauss's law",
  ],
  "Electrostatic Potential & Capacitance": [
    "Electric potential & potential difference",
    "Potential due to point charge / dipole / system",
    "Equipotential surfaces",
    "Potential energy of system of charges",
    "Conductors & dielectrics in electrostatics",
    "Capacitance & parallel plate capacitor",
    "Capacitors in series & parallel",
    "Effect of dielectric",
    "Energy stored in a capacitor",
  ],
  "Current Electricity": [
    "Electric current & drift velocity",
    "Ohm's law & resistivity",
    "Temperature dependence of resistance",
    "EMF, terminal voltage & internal resistance",
    "Cells in series & parallel",
    "Kirchhoff's laws",
    "Wheatstone bridge",
    "Meter bridge",
    "Potentiometer",
  ],
  "Moving Charges and Magnetism": [
    "Magnetic force on a moving charge",
    "Motion in magnetic field & cyclotron",
    "Biot-Savart law",
    "Ampere's circuital law",
    "Solenoid & toroid",
    "Force on current-carrying conductor",
    "Force between parallel currents",
    "Torque on current loop & magnetic dipole",
    "Moving coil galvanometer",
  ],
  "Magnetism and Matter": [
    "Bar magnet & magnetic field lines",
    "Magnetic dipole moment",
    "Earth's magnetism",
    "Magnetization & magnetic intensity",
    "Diamagnetic / paramagnetic / ferromagnetic substances",
    "Hysteresis",
  ],
  "Electromagnetic Induction": [
    "Magnetic flux",
    "Faraday's laws",
    "Lenz's law & energy conservation",
    "Motional EMF",
    "Eddy currents",
    "Self-inductance",
    "Mutual inductance",
    "AC generator",
  ],
  "Alternating Currents": [
    "AC voltage applied to R / L / C",
    "Phasor representation",
    "Series LCR circuit",
    "Resonance & quality factor",
    "Power in AC circuit & power factor",
    "Wattless current",
    "LC oscillations",
    "Transformers",
  ],
  "Electromagnetic Waves": [
    "Displacement current",
    "Maxwell's equations (qualitative)",
    "EM wave properties",
    "EM spectrum & uses",
  ],
  "Ray Optics & Optical Instruments": [
    "Reflection by spherical mirrors",
    "Refraction & Snell's law",
    "Total internal reflection",
    "Refraction at spherical surfaces & lenses",
    "Lens maker's formula & combination of lenses",
    "Refraction & dispersion by prism",
    "Scattering of light",
    "Microscope (simple & compound)",
    "Telescope (refracting & reflecting)",
  ],
  "Wave Optics": [
    "Huygens' principle",
    "Coherent sources & interference",
    "Young's double-slit experiment",
    "Diffraction at single slit",
    "Resolving power of optical instruments",
    "Polarization & Brewster's law",
  ],
  "Dual Nature of Radiation & Matter": [
    "Photoelectric effect",
    "Einstein's photoelectric equation",
    "Wave nature of matter",
    "de Broglie wavelength",
    "Davisson-Germer experiment",
  ],
  "Atoms": [
    "Alpha-particle scattering & Rutherford model",
    "Bohr's model of hydrogen atom",
    "Energy levels & line spectrum",
    "de Broglie's explanation of Bohr's quantization",
  ],
  "Nuclei": [
    "Composition & size of nucleus",
    "Mass-energy & binding energy",
    "Nuclear force",
    "Radioactivity (α, β, γ)",
    "Law of radioactive decay & half-life",
    "Nuclear fission",
    "Nuclear fusion",
  ],
  "Semiconductor Electronics": [
    "Energy bands in solids",
    "Intrinsic & extrinsic semiconductors",
    "p-n junction & diode",
    "Diode as rectifier (half & full wave)",
    "Special diodes (Zener, photodiode, LED, solar cell)",
    "Logic gates",
  ],

  // ================= CHEMISTRY =================
  "Solutions": [
    "Types & concentration of solutions",
    "Solubility & Henry's law",
    "Vapour pressure & Raoult's law",
    "Ideal & non-ideal solutions",
    "Colligative properties",
    "Osmotic pressure",
    "Abnormal molar mass & van't Hoff factor",
  ],
  "Electrochemistry": [
    "Galvanic cells & electrode potential",
    "Nernst equation",
    "Conductance of electrolytic solutions",
    "Kohlrausch's law",
    "Electrolysis & Faraday's laws",
    "Batteries (primary & secondary)",
    "Fuel cells",
    "Corrosion",
  ],
  "Chemical Kinetics": [
    "Rate of reaction & factors affecting it",
    "Rate law, order & molecularity",
    "Integrated rate equations (zero & first order)",
    "Half-life",
    "Pseudo first-order reactions",
    "Arrhenius equation & activation energy",
    "Collision theory (qualitative)",
  ],
  "d- and f-Block Elements": [
    "General properties of transition metals",
    "Variable oxidation states",
    "Catalytic & magnetic properties",
    "Coloured ions & complex formation",
    "Lanthanoids & lanthanoid contraction",
    "Actinoids",
    "Preparation & properties of KMnO4 and K2Cr2O7",
  ],
  "Coordination Compounds": [
    "Werner's theory & terminology",
    "Ligands & coordination number",
    "IUPAC nomenclature",
    "Isomerism (structural & stereo)",
    "VBT & hybridisation",
    "Crystal Field Theory",
    "Stability & importance of coordination compounds",
  ],
  "Haloalkanes and Haloarenes": [
    "Classification & nomenclature",
    "Methods of preparation",
    "Physical properties",
    "SN1 & SN2 mechanisms",
    "Elimination reactions",
    "Reactions of haloarenes",
    "Polyhalogen compounds & environmental effects",
  ],
  "Alcohols, Phenols & Ethers": [
    "Classification & nomenclature",
    "Preparation of alcohols & phenols",
    "Physical properties & H-bonding",
    "Chemical reactions of alcohols",
    "Acidic nature & reactions of phenols",
    "Preparation & reactions of ethers",
    "Commercially important compounds",
  ],
  "Aldehydes, Ketones & Carboxylic Acids": [
    "Nomenclature & structure",
    "Preparation of aldehydes & ketones",
    "Nucleophilic addition mechanism",
    "Reactions due to α-hydrogen",
    "Oxidation & reduction reactions",
    "Carboxylic acids — preparation",
    "Carboxylic acids — properties & reactions",
  ],
  "Amines": [
    "Classification, structure & nomenclature",
    "Preparation methods",
    "Physical & basic properties",
    "Chemical reactions of amines",
    "Diazonium salts & their reactions",
    "Importance of amines",
  ],
  "Biomolecules": [
    "Carbohydrates — mono / di / polysaccharides",
    "Proteins — amino acids & structure",
    "Enzymes",
    "Vitamins",
    "Nucleic acids (DNA & RNA)",
  ],

  // ================= MATHS =================
  "Relations and Functions": [
    "Types of relations",
    "Equivalence relations",
    "Types of functions (1-1, onto)",
    "Composition of functions",
    "Invertible functions",
    "Binary operations",
  ],
  "Inverse Trigonometric Functions": [
    "Basic concepts & domains",
    "Principal value branches",
    "Properties of inverse trig functions",
    "Graphs of inverse trig functions",
  ],
  "Matrices": [
    "Order & types of matrices",
    "Matrix operations",
    "Transpose, symmetric & skew-symmetric",
    "Elementary row/column operations",
    "Inverse of a matrix by elementary operations",
  ],
  "Determinants": [
    "Determinant of a square matrix",
    "Properties of determinants",
    "Area of triangle",
    "Minors & cofactors",
    "Adjoint & inverse of a matrix",
    "Solving linear equations by matrix method",
    "Consistency of system",
  ],
  "Continuity & Differentiability": [
    "Continuity at a point & on interval",
    "Algebra of continuous functions",
    "Differentiability",
    "Chain rule & composite functions",
    "Implicit differentiation",
    "Derivatives of inverse trig functions",
    "Logarithmic differentiation",
    "Parametric forms",
    "Second-order derivatives",
    "Rolle's & Mean Value theorems",
  ],
  "Applications of Derivatives": [
    "Rate of change",
    "Increasing & decreasing functions",
    "Tangents & normals",
    "Approximations",
    "Maxima & minima (first & second derivative tests)",
  ],
  "Integrals": [
    "Indefinite integrals & standard forms",
    "Integration by substitution",
    "Integration by parts",
    "Integration by partial fractions",
    "Definite integrals as limit of sum",
    "Fundamental theorem of calculus",
    "Properties of definite integrals",
  ],
  "Applications of Integrals": [
    "Area under simple curves",
    "Area between two curves",
  ],
  "Differential Equations": [
    "Order & degree",
    "General & particular solutions",
    "Variables separable",
    "Homogeneous differential equations",
    "Linear differential equations",
  ],
  "Vectors": [
    "Scalars & vectors basics",
    "Types of vectors",
    "Addition & section formula",
    "Components & direction cosines",
    "Dot (scalar) product",
    "Cross (vector) product",
    "Scalar triple product",
  ],
  "Three-Dimensional Geometry": [
    "Direction cosines & ratios",
    "Equation of a line in space",
    "Angle between two lines",
    "Shortest distance between skew lines",
    "Equation of a plane",
    "Distance of a point from a plane",
    "Angle between planes",
    "Coplanarity of lines",
  ],
  "Linear Programming": [
    "Mathematical formulation of LPP",
    "Graphical method of solution",
    "Feasible & infeasible regions",
    "Optimal solution & corner-point method",
    "Different types of LPP problems",
  ],
  "Probability": [
    "Conditional probability",
    "Multiplication theorem",
    "Independent events",
    "Total probability theorem",
    "Bayes' theorem",
    "Random variables & probability distribution",
    "Mean & variance",
    "Bernoulli trials & binomial distribution",
  ],
};

// Helper: returns the canonical sub-topic list for a chapter, or [] if the
// chapter is unknown (so the form can fall back to a generic input).
export function getSubtopicsForChapter(chapterName: string): string[] {
  return CHAPTER_SUBTOPICS[chapterName] || [];
}

// Derive an overall confidence from a per-sub-topic confidence map.
// Worst sub-topic wins: any "bad" → "bad", else any "average" → "average",
// else "good". Returns undefined if the map is empty.
export function deriveOverallConfidence(
  m: Record<string, "good" | "average" | "bad"> | undefined,
): "good" | "average" | "bad" | undefined {
  if (!m) return undefined;
  const vals = Object.values(m);
  if (vals.length === 0) return undefined;
  if (vals.includes("bad")) return "bad";
  if (vals.includes("average")) return "average";
  return "good";
}
